runtime : nodejs20

handlers:
  - url : /
    static_files : app.html
    upload : app.html

  - url : /second.html
    static_files : second.html
    upload : second.html
    
  - url: /.*\.html
    static_files: \1
    upload: (.*\.html)
